Fix issue #4 - AttributeError: 'NoneType'
Since this fix is for a time out issue:
`AttributeError: 'NoneType' object has no attribute 'get_text' #4 `. It might not be needed in all machines, hence, I believe it's better to have it in a different script as an extra option.